#!/usr/bin/env python

import subprocess32 as subprocess
import sys


def main():
    code = subprocess.call(['eci', 'test', '--head-only'])
    if code != 0:
        print 'Tests failed. To push anyways, run `git push --no-verify`.'
        sys.exit(code)

if __name__ == "__main__":
    main()
